# -*- coding: utf-8 -*-
"""week3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BqVHEeM-q_pfb7Sw6AFekC4iGDS0uVhM
"""

!pip install PyPDF2 gtts nltk

import nltk
nltk.download('punkt')

from google.colab import files
uploaded = files.upload()

file_name = list(uploaded.keys())[0]
print("Uploaded:", file_name)

from PyPDF2 import PdfReader
import re

def extract_clean_text(file):
    reader = PdfReader(file)
    text = ""

    for page in reader.pages:
        t = page.extract_text()
        if t:
            text += t + " "

    # CLEAN TEXT
    text = re.sub(r'\s+', ' ', text)  # remove extra spaces
    text = re.sub(r'[^A-Za-z0-9., ]+', '', text)  # remove junk symbols

    return text

pdf_text = extract_clean_text(file_name)
print(pdf_text[:1000])

import nltk

try:
    sentences = nltk.sent_tokenize(pdf_text)
except:
    sentences = pdf_text.split(".")

print("Total sentences:", len(sentences))

def generate_keycards(sentences, num_cards=15):
    clean = []

    for s in sentences:
        words = s.split()
        if 8 < len(words) < 25:
            clean.append(s.strip())

    keycards = clean[:num_cards]
    return keycards

keycards = generate_keycards(sentences)

print("\n📚 KEYCARDS:\n")
for i, k in enumerate(keycards):
    print(f"{i+1}. {k}\n")

from gtts import gTTS
from IPython.display import Audio
import os

def speak(text):
    try:
        tts = gTTS(text=text[:500])  # limit length (important)
        tts.save("voice.mp3")
        return Audio("voice.mp3")
    except Exception as e:
        print("Voice error:", e)
        return None

choice = int(input("Enter keycard number to hear: ")) - 1

if 0 <= choice < len(keycards):
    print("\nPlaying:", keycards[choice])
    audio = speak(keycards[choice])
    if audio:
        display(audio)
else:
    print("Invalid choice")

import random

def generate_mcqs(sentences, num_q=10):
    mcqs = []

    valid_sentences = [s for s in sentences if len(s.split()) > 10]

    for s in valid_sentences[:num_q]:
        words = list(set(s.split()))

        if len(words) < 6:
            continue

        answer = random.choice(words)
        question = s.replace(answer, "_____")

        options = random.sample(words, 4)
        if answer not in options:
            options[0] = answer

        random.shuffle(options)

        mcqs.append({
            "q": question,
            "options": options,
            "ans": answer
        })

    return mcqs

mcqs = generate_mcqs(sentences, 10)

print("Generated MCQs:", len(mcqs))

def run_quiz(mcqs):
    score = 0

    for i, q in enumerate(mcqs):
        print(f"\nQ{i+1}: {q['q']}")

        for idx, opt in enumerate(q['options']):
            print(f"{idx+1}. {opt}")

        user = input("Enter option number: ")

        try:
            user = int(user) - 1

            if 0 <= user < len(q['options']):
                if q['options'][user] == q['ans']:
                    print("✅ Correct")
                    score += 1
                else:
                    print(f"❌ Wrong → {q['ans']}")
            else:
                print("Invalid choice")
        except:
            print("Invalid input")

    print(f"\n🔥 Final Score: {score}/{len(mcqs)}")

run_quiz(mcqs)