# -*- coding: utf-8 -*-
"""week2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_FhmK6Nhthb6qJl-p41K1DEcjIEaV9E8
"""

username = "ayaanamp"
token = "YOUR_GITHUB_TOKEN"   # paste your token here
repo = "AI-Edu-Generator"

!git clone https://{username}:{token}@github.com/{username}/{repo}.git

# Commented out IPython magic to ensure Python compatibility.
# %cd AI-Edu-Generator

# Rename your file properly first in Colab (IMPORTANT)
!cp /content/Week2_PDF_Flashcards.ipynb /content/AI-Edu-Generator/

!git config --global user.email "ayaanmajeedpasha@google.com"
!git config --global user.name "ayaanamp"

!git add .
!git commit -m "Week 2: PDF input + Flashcards + MCQ"
!git push

!mkdir week1
!mkdir week2

!mv week1_mcq.ipynb week1/
!mv Week2_PDF_Flashcards.ipynb week2/

!git add .
!git commit -m "Organized project structure"
!git push

readme = """
# AI Edu Generator

## Week 1
- MCQ Generator

## Week 2
- PDF Input
- Flashcards Generator
- Key Points Extraction

## Tech Used
- Python
- Google Colab
- PyPDF2

## Status
In Progress
"""

with open("README.md", "w") as f:
    f.write(readme)

!pip install PyPDF2

import PyPDF2
import random

def extract_text_from_pdf(file):
    text = ""
    reader = PyPDF2.PdfReader(file)

    for page in reader.pages:
        text += page.extract_text()

    return text

def clean_text(text):
    return text.replace("\n", " ").strip()

def generate_flashcards(text):
    sentences = text.split(".")
    cards = []

    for s in sentences[:10]:
        if len(s) > 20:
            cards.append(("Explain: " + s.strip(), s.strip()))

    return cards

def get_key_points(text):
    sentences = text.split(".")
    return [s.strip() for s in sentences if len(s.split()) > 8][:10]

def generate_mcq(text):
    sentences = text.split(".")
    mcqs = []

    for s in sentences[:5]:
        if len(s) > 20:
            correct = s.strip()
            options = [correct, "Option A", "Option B", "Option C"]
            random.shuffle(options)

            mcqs.append({
                "question": s.strip(),
                "options": options,
                "answer": correct
            })

    return mcqs

from google.colab import files

uploaded = files.upload()

file_name = list(uploaded.keys())[0]

text = extract_text_from_pdf(file_name)
cleaned = clean_text(text)

cards = generate_flashcards(cleaned)

for q, a in cards:
    print("Q:", q)
    print("A:", a)
    print()

points = get_key_points(cleaned)

for p in points:
    print("-", p)

mcqs = generate_mcq(cleaned)

for m in mcqs:
    print("Q:", m["question"])
    print("Options:", m["options"])
    print("Answer:", m["answer"])
    print()